version: "3.8"

services:
  dheartbeat:
    container_name: dheartbeat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:80" # Map host port 8080 to container port 80

